### PR TITLE
Cleanup lua code

### PR DESCRIPTION
**Pull request by ctiquet-systran**
Hi Yoon,

I did a little cleanup of your lua scripts.
We plan to add new features to seq2seq-attn and use it in our translation engines, and It's important for us to start with a clean code base.
The current inconsistencies make the code unusable in a team environment and it would be great if you could integrate this. Otherwise, we won't be able to merge future upstream changes easily.

The patch is really big because basically all lines have been changed so let me know if there is anything unclear.

Patch details:

- remove redundant options parsing (cmd:parse was unnecessary called twice in several scripts)

- cleanup requires (remove unused, add missing, harmonize call style)
  The code was executing just fine when using the torch interactive interpreter (th command) that makes an extra effort to find lua scripts, but not with the lua interpreter.
  For example, the dot in a require instruction (eg: 'script.lua') is used as a path separator in lua.
  That means lua will try to find a script named 'lua.lua' located in the 'script' subdir, which is obvisouly not what you intended.

- cleanup trailing whitespaces

- cleanup mixed indentation: 2 spaces, no tabs
  Before this, the indentation was a mix of 1/2/3 spaces and tabs that made the code unreadable depending on which text editor you used). It would help to keep this rule from now on.

### CODE REVIEW

**Comment by ctiquet-systran** [comment]
A little precision regarding the requires cleanup:

I just came across the following issue #10, where require 'util' didn't work with torch.
My first iteration to make it work with lua broke your fix you did in this issue.

I fixed it in my second commit, it now works both with th and lua interpreters.
I use 'dofile' instead of 'require' to load your scripts, which is safer. See commit message for details.

Cyril

**Comment by yoonkim** [comment]
thanks! merged

**Comment by srush** [comment]
Hey Cyril, 

Thanks for using seq2seq-attn. Let us know if there is anything else we can do to make it usable for your purposes. It is certainly research code, but it is getting better and we are very willing to add/take pull request for more features. 

Cheers,
Sasha

**Comment by ctiquet-systran** [comment]
Hi Sasha,

Thank you both for your quick replies, amazing work you've done here.
Actually yes I think I will have at least one more pull request to submit in the next few days (for making the code a little more flexible to be able to call it more easily in command line as well as from C/C++ libraries).
I'll keep you posted!

Cyril

**Pull request merged**
